
// WHAT IS THIS FILE?
// This file defines the "shape" of a Recommendation document in MongoDB.
// Each recommendation says:
//   "For product X (source), we recommend product Y (recommended)
//    with a score of Z and here's why."
//
// HOW THIS FITS IN THE APP:
// 1. User selects a product (e.g., "Amul Milk")
// 2. The recommendation engine (built by Anshu in Task B5) scores
//    all same-category products and picks the top 5
// 3. The AI explainer (your Task B7!) generates a reason sentence
// 4. The results are SAVED here so we don't recalculate every time
//    (this is called "caching" — saves time and API quota)
// 5. When the user views recommendations, we just READ from here
//    (fast!) instead of re-running the engine (slow!)
//
// RELATIONSHIPS:
//   This schema has TWO references to the Product collection:
//   - sourceProductId: the product the user selected
//   - recommendedProductId: the product being recommended
//
//   Product Collection          Recommendation Collection
//   ┌──────────────────┐       ┌─────────────────────────────┐
//   │ _id: "abc123"    │◄──────│ sourceProductId: "abc123"   │
//   │ name: "Amul Milk"│       │                             │
//   └──────────────────┘       │                             │
//                              │                             │
//   ┌──────────────────┐       │                             │
//   │ _id: "def456"    │◄──────│ recommendedProductId:"def456│
//   │ name: "Nandini   │       │ recommendationScore: 96.8   │
//   │        Milk"     │       │ reason: "Same category..."  │
//   └──────────────────┘       └─────────────────────────────┘
// ============================================================

// Step 1: Import mongoose
import mongoose from 'mongoose';

// Step 2: Define the Recommendation Schema
const recommendationSchema = new mongoose.Schema(
  {
    // ---- sourceProductId ----
    // The product that the user SELECTED (the one they're looking at).
    // e.g., If the user is viewing "Amul Milk", this stores Amul Milk's _id.
    //
    // `type: mongoose.Schema.Types.ObjectId` → stores a MongoDB ObjectId
    // `ref: 'Product'` → links to the Product collection (for .populate())
    // `required: true` → every recommendation must have a source product
    sourceProductId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Product',
      required: [true, 'Source product ID is required'],
    },

    // ---- recommendedProductId ----
    // The product being RECOMMENDED as an alternative.
    // e.g., If "Nandini Milk" is recommended as a substitute for "Amul Milk",
    // this stores Nandini Milk's _id.
    //
    // Also references the Product collection — same syntax as above.
    recommendedProductId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Product',
      required: [true, 'Recommended product ID is required'],
    },

    // ---- recommendationScore ----
    // A number from 0 to 100 showing HOW GOOD this recommendation is.
    // The formula (from the spec) is:
    //   score = 40×categoryMatch + 20×priceSimilarity + 20×(rating/5) + 20×inStock
    //
    // Higher score = better match. For example:
    //   - Score 96.8 → excellent match (same category, similar price, high rating, in stock)
    //   - Score 40.0 → decent match (same category but expensive, low rating, out of stock)
    //
    // `min: 0, max: 100` → VALIDATION: score must be between 0 and 100
    //   If the engine somehow produces a score of 150, this will reject it.
    recommendationScore: {
      type: Number,
      required: [true, 'Recommendation score is required'],
      min: [0, 'Score cannot be less than 0'],
      max: [100, 'Score cannot be more than 100'],
    },

    tags : {
      type: [String],
      default : [],
    }
,
    // ---- reason ----
    // A human-readable explanation of WHY this product is recommended.
    // This is generated by the AI Explainer (Gemini API) or a template fallback.
    //
    // Example: "Nandini Milk is a great alternative — it's in stock,
    //           similarly priced, and has a higher customer rating."
    //
    // This field is NOT required because:
    //   - The recommendation can exist before the AI generates the reason
    //   - If AI fails, the template fallback will fill this in
    //
    // WHY CACHE THE REASON?
    // We save the AI-generated text here so we DON'T have to call the
    // Gemini API every time someone views recommendations.
    //   - POST /generate-recommendations → runs engine + AI, saves here
    //   - GET /recommendations/:productId → just reads from here (fast!)
    reason: {
      type: String,
    },
  },
  {
    // ---- timestamps option ----
    // Adds `createdAt` and `updatedAt` automatically.
    // `createdAt` tells us when this recommendation was generated.
    timestamps: true,
  }
);

recommendationSchema.index(
  { sourceProductId: 1, recommendedProductId: 1 },
  { unique: true }
);
recommendationSchema.index({ sourceProductId: 1, recommendationScore: -1 });

// Step 3: Create and Export the Model
// "Recommendation" → MongoDB collection will be called "recommendations"
const Recommendation = mongoose.model('Recommendation', recommendationSchema);

export default Recommendation;
